name: test-and-lint
on:
  push:
    branches: [ master, stress-test ]
  pull_request:
jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  Automated-Tests:
    name: Automated-Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Support LTS versions based on https://nodejs.org/en/about/releases/
        node-version: ['14', '16', '18']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run stress tests
        run: npm run stress-test-auto
